services:
  - type: web
    name: race-vision  # Change this to your service name
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    routes:
      - src: /.*
        dest: /index.html